export const REQUEST_CURRENT_PICTURE = 'REQUEST_CURRENT_PICTURE';

export const RECEIVE_CURRENT_PICTURE = 'RECEIVE_CURRENT_PICTURE';
export const FAIL_CURRENT_PICTURE = 'FAIL_CURRENT_PICTURE';


export const ADD_PICTURE_TO_HISTORY = 'ADD_PICTURE_TO_HISTORY';
export const REMOVE_PICTURE_FROM_HISTORY = 'REMOVE_PICTURE_FROM_HISTORY';
